/goal_rotator_node:
  ros__parameters:
    pose_topic: "/goal_pose"
    goal_point_topic: "/goal_point"
    planner_status_topic: "/far_reach_goal_status"
    planner_cmd_vel_topic: "/cmd_vel"
    planner_cmd_vel_stamped_topic: "/cmd_vel"
    use_stamped_cmd_vel: true
    max_rotation_speed: 1.0
    min_rotation_speed: 0.0
    angle_tolerance: 20.0
    kp: 1.5
    odom_topic: "/robot_odom"
    output_topic: "/cmd_vel_out"
    output_hz: 50.0