[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:xvfb]
command=/bin/bash -c "/usr/bin/Xvfb :99 -screen 0 1920x1080x24 +iglx -ac"
autorestart=true
priority=100
stdout_logfile=/tmp/intern-vnc/xvfb.log
stderr_logfile=/tmp/intern-vnc/xvfb.log
environment=DISPLAY=":99"
user=intern

[program:fluxbox]
command=/bin/bash -c "sleep 2 && /usr/bin/fluxbox -display :99"
autorestart=true
priority=200
stdout_logfile=/tmp/intern-vnc/fluxbox.log
stderr_logfile=/tmp/intern-vnc/fluxbox.log
environment=DISPLAY=":99"
user=intern

[program:x11vnc]
command=/bin/bash -c "sleep 4 && /usr/bin/x11vnc -display :99 -forever -shared -rfbport 5900 -nopw -noxdamage -noxkb -nowf -nowcr -noshm"
autorestart=true
priority=300
stdout_logfile=/tmp/intern-vnc/x11vnc.log
stderr_logfile=/tmp/intern-vnc/x11vnc.log
environment=DISPLAY=":99"
user=intern

[program:novnc]
command=/usr/bin/websockify --web=/usr/share/novnc 6080 localhost:5900
autorestart=true
priority=400
stdout_logfile=/tmp/intern-vnc/novnc.log
stderr_logfile=/tmp/intern-vnc/novnc.log
user=intern