tsp_solver:
  ros__parameters: {}

inspection_planner:
  ros__parameters:
    inspection_poses_topic: "/inspection_poses"
    nav_action_server_name: "/nav_to_pose"
    tsp_solver: "/solve_tsp"
    tsp_waypoints_topic: "/inspection_waypoints"
    tsp_distance_matrix_topic: "/tsp_distance_matrix"
    pose_merge_distance_tolerance: 0.3
    pose_merge_angular_tolerance: 0.349066  # 20 degrees in radians
    use_tsp: true
