tsp_solver:
  ros__parameters:
    service_name: "/solve_tsp"
    solver_algorithm: "brute_force"
    random_seed: 42
    brute_force_max_nodes: 7
    symmetry_tolerance: 0.01
    qos_depth: 1 

inspection_planner:
  ros__parameters:
    inspection_poses_topic: "/inspection_poses"
    nav_action_server_name: "/nav_to_pose"
    tsp_solver: "/solve_tsp"
    tsp_waypoints_topic: "/inspection_waypoints"
    tsp_distance_matrix_topic: "/tsp_distance_matrix"
    pose_merge_distance_tolerance: 0.3
    pose_merge_angular_tolerance: 0.349066  # 20 degrees in radians
    planner_mode: rolling-tsp             #  ascending, tsp-once, tsp, rolling-tsp
    do_retry: false
    rolling_window_size: 5
    
inspection_logger:
  ros__parameters:
    edge_gradient_max_len: 10.0
    edge_gradient_min_len: 1.0